config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get  "/candidate" , to: "home#candidate", as: :candidate
  get  "/detail/:data" , to: "home#detail", as: :detail
  get "admindata/:d" , to: "home#admindata", as: :admindata
  get  "/admin" , to: "home#admin", as: :admin
  get  "apply" , to: "home#apply", as: :apply
  post "/create_detail/:id" , to: "home#create_detail" ,as: :create_detail
  get "data/:id", to: "home#data",as: :data
  post "updatedata/:id", to: "home#updatedata",as: :updatedata
  get "interviewer", to: "home#interviewer", as: :interviewer
  get "all_user_list", to: "home#all_user_list", as: :all_user_list
  get "track/:id" , to: "home#track", as: :track
  get "setdrivedate/", to: "home#setdrivedate", as: :setdrivedate
  post "set/", to: "home#set" , as: :set
  get "all_date/", to: "home#all_date" , as: :all_date
  get "remove/:id", to: "home#remove" ,as: :remove
  get "edit_user_profile/:id", to: "home#edit_user_profile" , as: :edit_user_profile
  get "Shedule_Interview/:id", to: "home#Shedule_Interview" , as: :Shedule_Interview
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  
    @drive_date =Setdate.all 
    if current_user
      if current_user.role == "user"
        redirect_to candidate_path 
      elsif current_user.role == "admin"
        redirect_to admin_path
      elsif current_user.role == "interviewer"
        redirect_to interviewer_path
      end
    end  
  end

  def candidate
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end  
  def interviewer
    if current_user
      @n = current_user.name
      @list = User.where(inter:@n)
    else
      redirect_to new_user_session_path
    end
  end  
 
  def data
    unless user_signed_in?
     redirect_to new_user_session_path
    end
    @user =User.find(params[:id])
    
  end  

    

  def updatedata
    @data = User.find(params[:id])
    @data.update(params.require(:user).permit(:name,:email,:inter,:first,:password,:second,:third,:role,:attend_time,:interview_date,:zoom_link))
    redirect_to admin_path
  end

  def detail
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @date = Mydate.where(profile:params[:data])
  end  

  def admindata
    @data = params[:d]
  end  


  def create_detail 
    @id = User.find(params[:id])
    if params[:ten]!="" && params[:year]!="" && params[:percentage]!="" && params[:twelth]!="" && params[:year1]!="" && params[:percentage1]="" && params[:digree]!="" && params[:year2]!="" && params[:percentage2]!="" && params[:profile]!=""
      if @id.mydates.pluck(:profile).include?(params[:profile]) && @id.mydates.pluck(:date).include?(params[:date])
       flash[:notice] = "you have already Applied for this drive of profile #{params[:profile]} which held on date #{params[:date]}"
       redirect_to apply_path
      else  
        @id.mydates.create(:ten => params[:ten],:year => params[:year],:percentage => params[:percentage],:twelth => params[:twelth],:year1 => params[:year1],:percentage1 => params[:percentage1],:digree => params[:digree],:year2 => params[:year2],:percentage2 => params[:percentage2],:date => params[:date],:profile => params[:profile])
        flash[:notice] = "Successfully Applied"  
        redirect_to candidate_path
      end  
    else
      flash[:notice] = "Value not be empty"  
      redirect_to apply_path  
    end  
  end  


   
  def apply
    @all_date = Setdate.all
    if current_user

    else
      redirect_to root_path
    end  


  end

  def all_user_list
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @user = User.all    
  end  




  def admin
    @drive = 0
    if current_user
      @drive = Mydate.all
      if current_user.role == "admin"
        @d = Mydate.all
        @drive = @d
      end  
    else
      redirect_to root_path
    end  


  end  

   
  def track
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @user = User.find(params[:id])   
  end  
   
  def setdrivedate
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    
  end
  

  def set
    @a = Setdate.new(:date => params[:date],:profile => params[:profile])
    @data = params[:date][0,4].to_i
    @y = DateTime.now.strftime('%Y').to_i
    if @data >= @y
      if @a.save
      flash[:notice] = "Successfully date and Profile updated #{params[:date]}"  
      redirect_to setdrivedate_path
      end
    elsif params[:date]=="" && params[:profile]==""
      flash[:notice] = "empty field are there"
      redirect_to setdrivedate_path
    elsif @data <= @y
      flash[:notice] = "The given Date Cant Be set"
      redirect_to setdrivedate_path
    elsif
      unless user_signed_in?
        redirect_to new_user_session_path
      end
    end   

  end

    

  def all_date
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @all_date = Setdate.all
  end   

    
  def remove
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @del = Setdate.find(params[:id])
    @date = Mydate.where(date:@del.date)
    @date.each do |i|
      i.destroy
    end  
    @del.destroy
    redirect_to admin_path
  end  
  
  def edit_user_profile
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @user = User.find(params[:id])
  end  

  def Shedule_Interview
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @user = User.find(params[:id])
  end  

  private
  def article_params(*args)
    params.require(:setdate).permit(:date,:profile)
  end
  

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/Shedule_Interview.html.erb
<% if current_user.role=="admin" %>
    <!--  -->
    <div class="col-lg-5 mx-lg-auto card shadow mt-5">
        <div class="card-header">
            <h3 class="card-title text-center text-danger">INTERVIEW</h3>
        </div>
        <div class="card-body">


            <%= form_with model:@user,method: :post, url:updatedata_path(@user.id) do |form| %>


                <div class="form-group mb-2">
                    <%= form.label :Name%><br>
                        <%= form.text_field :name , class: "form-control form-control-lg" %>
                </div>



                <div class="form-group mb-2">
                    <%= form.label :email%><br>
                        <%= form.text_field :email, class: "form-control form-control-lg" %>
                </div>

                <div class="form-group mb-2">
                    <%if @user.first.empty?%>
                        <%= form.label :First_round%><br>
                        <%= form.text_field :first, class: "form-control form-control-lg" %>
                        <%= form.label :Second_round%><br>
                        <%= form.text_field :second, class: "form-control form-control-lg disabled", :disabled => true  %>
                        <%= form.label :Third_round%><br>
                        <%= form.text_field :third, class: "form-control form-control-lg disabled", :disabled => true  %>
                    <%else%>
                        <%if @user.second.empty?%>
                            <%= form.label :First_round%><br>
                            <%= form.text_field :first, class: "form-control form-control-lg disabled", :disabled => true  %>
                            <%= form.label :Second_round%><br>
                            <%= form.text_field :second, class: "form-control form-control-lg disabled"%>
                            <%= form.label :Third_round%><br>
                            <%= form.text_field :third, class: "form-control form-control-lg disabled", :disabled => true  %>
                        <%else%>
                            <%= form.label :First_round%><br>
                            <%= form.text_field :first, class: "form-control form-control-lg disabled", :disabled => true  %>
                            <%= form.label :Second_round%><br>
                            <%= form.text_field :second, class: "form-control form-control-lg disabled", :disabled => true  %>
                            <%= form.label :Third_round%><br>
                            <%= form.text_field :third, class: "form-control form-control-lg disabled" %>
                        <%end%>
                    <%end%>
                </div>  

                <div class="form-group mb-2">
                    <%= form.label :Time%><br>
                        <%= form.text_field :attend_time, class: "form-control form-control-lg" %>
                </div>

                <div class="form-group mb-2">
                    <%= form.label :interview_date%><br>
                        <%= form.text_field :interview_date, class: "form-control form-control-lg" %>
                </div>


                <div class="form-group mb-2">
                    <%= form.label :Interviewer_name%><br>
                        <%= form.text_field :inter, class: "form-control form-control-lg" %>
                </div>

                <div class="form-group mb-2">
                    <%= form.label :Zoom_link%><br>
                        <%= form.text_field :zoom_link, class: "form-control form-control-lg" %>
                </div>



                <%= form.submit "Press" %>
        </div>
        <% end %>

    </div>
    </div>
    <!--  -->
    <% else%>
        <%= "sorry invalid user permission" %>
            <%end%>

app/views/home/admin.html.erb
<div class="bag">


<%ar=[]%>

<%if @drive %>
<% @drive.each do |i|%>
  <% unless ar.include?(i.profile) %> 
    <%ar.push(i.profile)%>
 
   <%end%>
<% end %>
<%end%>






   <div class="container mt-5">
    <ul class="list-group">
      <li class="list-group-item text-center">ADMIN DASHBOARD</li>
    
    
      <li class="list-group-item list-group-item-danger">

        <% if current_user.role =="admin" %>

        <% if ar.empty?()%>
            <h1> List is empty no user applied for drive </h1>
        <% else%>
        <% ar.each do |i|%>
        <%= link_to i,detail_path(i) %><br>
        <% end %> 

        <!-- <% @drive.each do |a|%>
        <%=a.profile%> 
        <%end%> -->

        <%end%>
                  
        <%end%>

      </li>


      <li class="list-group-item list-group-item-primary">
                 

 <% if current_user.role =="admin" %>

 <%= link_to "all_user" ,all_user_list_path %>
<br>
 <%= link_to "Set date and Profile Of Drive" ,setdrivedate_path %>
 <br>
 <%= link_to "all_drive_date and Profile" ,all_date_path %>
<% else%>
 <%= "sorry invalid user permission"%>
 <%end%>

   

      </li>
    
    </ul>

   </div>







 </div>

app/views/home/admindata.html.erb
<%= @data %>

app/views/home/all_date.html.erb
<% if current_user.role =="admin" %>
<table>
<% @all_date.each do |i|%>
     <tr>
        <td>
            <%= i.date%> : <%= i.profile%> <%= link_to "delete" , remove_path(i.id) %>
            
        </td>
     </tr>

<%end%> 
</table>
<br>
<%= link_to "admin" ,admin_path %>

<% else%>
<%= "sorry invalid user permission"%>
<%end%>

app/views/home/all_user_list.html.erb
<% if current_user.role =="admin" %>
<% @user.each do |i|%>
<%= i.name%> 
<%= link_to "Edit" ,edit_user_profile_path(i.id) %> <br>
<%end%>


<% else%>
<%= "sorry invalid user permission"%>
<%end%>

app/views/home/apply.html.erb
<div class="container">
  <% if notice %>
  <%=notice%>
<%end%>


  <div class="row">

    <div class="col-6 mt-5">
      <div class="text-right"> DRIVE DATES</div>
      <% @all_date.each do |i|%>

        <div class="row mt-3">

          <div class="col-md-6">
            <label>Date</label>
          </div>
          <div class="col-md-6">
            <p>
              <%= i.date%>
            </p>
          </div>

        </div>
        <%end%>
    </div>


    <div class="col-lg-5 mx-lg-auto card shadow mt-5">
      <div class="card-header">
        <h3 class="card-title text-center">FRIVE FORM</h3>
      </div>
      <div class="card-body">



        <%= form_with method: :post, url:create_detail_path(current_user.id) do |form| %>


          <div class="form-group mb-2">
            <%= form.label :"10TH"%><br>
              <%= form.text_field :ten , class: "form-control form-control-lg" %>
          </div>

          <div class="form-group mb-2">
            <%= form.label :Year_of_passing %><br>
              <%= form.text_field :year , class: "form-control form-control-lg" %>
          </div>

          <div class="form-group mb-2">
            <%= form.label :percentage %><br>
              <%= form.text_field :percentage , class: "form-control form-control-lg" %>
          </div>


          <div class="form-group mb-2">
            <%= form.label :"12TH"%><br>
              <%= form.text_field :twelth , class: "form-control form-control-lg" %>
          </div>

          <div class="form-group mb-2">
            <%= form.label :Year_of_passing%><br>
              <%= form.text_field :year1 , class: "form-control form-control-lg" %>
          </div>

          <div class="form-group mb-2">
            <%= form.label :percentage %><br>
              <%= form.text_field :percentage1 , class: "form-control form-control-lg" %>
          </div>

          <div class="form-group mb-2">
            <%= form.label :Digree%><br>
              <%= form.text_field :digree , class: "form-control form-control-lg" %>
          </div>

          <div class="form-group mb-2">
            <%= form.label :Year_of_passing %><br>
              <%= form.text_field :year2 , class: "form-control form-control-lg" %>
          </div>


          <div class="form-group mb-2">
            <%= form.label :percentage %><br>
              <%= form.text_field :percentage2 , class: "form-control form-control-lg" %>
          </div>

      
          <div class="form-group mb-2">
  <%= form.label :date%><br>
   <%= form.collection_select :date,Setdate.all,:date ,:date%>
  </div>

          <!-- <div class="form-group mb-2">
            <%= form.label :date %><br>
              <%= form.text_field :date , class: "form-control form-control-lg" %>
          </div> -->


          <!-- <div class="form-group mb-2">
            <%= form.label :profile %><br>
              <%= form.text_field :profile , class: "form-control form-control-lg" %>
          </div> -->

         
                <div class="form-group mb-2">
      <%= form.label :profile%><br>
       <%= form.collection_select :profile,Setdate.all,:profile ,:profile%>
      </div>

                <%= form.submit "Submit" %>
      </div>
      <% end %>

    </div>
  </div>

app/views/home/candidate.html.erb
<% if user_signed_in? %>
  <div class="col-lg-8 mt-5 text-center">
    <div class="card mb-4">
      <% if notice %>
        <%=notice%>
          <%end%>
            <div class="card-body">

              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Name</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">
                    <%= current_user.name%><br>
                  </p>
                </div>
              </div>

              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">
                    <%= current_user.email%><br>
                  </p>
                </div>
              </div>
              <hr>

              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">
                    <%= link_to "Apply" ,apply_path%>
                  </p>
                </div>

              </div>
              <hr>


              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">
                    <%= link_to "Track" , track_path(current_user.id) %>
                  </p>
                </div>

              </div>
              <hr>

            </div>

            <% end %>

    </div>

  </div>
  </div>
  </div>

app/views/home/data.html.erb
    
 <% if current_user.role =="admin" %>
<!--  -->
<%=@user.name%> <br>
<%=@user.email%> <br>
<% @a = Mydate.find_by(user_id:@user.id)%>
   <% if @a%>
   Profile:<%=@a.profile%> <br>
   Date:<%=@a.date%> <br>
   10th:<%=@a.ten%> <br>
   Passing Year:<%=@a.year%> <br>
   percentage:<%=@a.percentage%> <br>
   12th:<%=@a.twelth%> <br>
   year:<%=@a.year1%> <br>
   percentage:<%=@a.percentage1%> <br>
   Digree:<%=@a.digree%> <br>
   Year:<%=@a.year2%> <br>
   percentage:<%=@a.percentage2%>
 <%else%>
 
 <%end%>
     
 <!--  -->
<% else%>
<!--  -->
 <%= "sorry invalid user permission"%>
 <!--  -->
 <%end%>
 <!--  -->
<br>
 <%= link_to "Shedule_Interview",Shedule_Interview_path(@user.id)%>
    
    

app/views/home/edit_user_profile.html.erb
<% if current_user.role =="admin" %>
      <!--  -->
<div class="col-lg-5 mx-lg-auto card shadow mt-5">
  <div class="card-header">
    <h3 class="card-title text-center text-danger">EDIT</h3>
  </div>
<div class="card-body">


<%= form_with model:@user,method: :post, url:updatedata_path(@user.id)  do |form| %>


<div class="form-group mb-2">
<%= form.label :Name%><br>
 <%= form.text_field :name , class: "form-control form-control-lg"%>
</div>


<div class="form-group mb-2">
  <%= form.label :email%><br>
   <%= form.text_field :email, class: "form-control form-control-lg"%>
  </div>
  
  <div class="form-group mb-2">
    <%= form.label :Role_user%><br>
    <%= form.select :role, ["admin","interviewer","user"]%>
</div>
 
  
<%= form.submit "Set" %>  
</div>
<% end %>

</div>
</div>
<!--  -->



<% else%>
<%= "sorry invalid user permission"%>
<%end%>

app/views/home/index.html.erb
<div class="image">

    <div class="content">
        <h1>WALK IN DRIVE FOR CANDIDATES</h1>
        <P>we have organized walk in drive for different type of role for the candidates</P>
  
    </div>
     
        
  

    <table class="text-white mtop">
        <tr>
          <th>Date</th>
          <th>Profile</th>
        </tr>
        <% @drive_date.each do |i| %>
        <tr>
          <td><%=i.date%></td>
          <td><%=i.profile%></td>
        </tr>
        <%end%>
      </table>
  
</div>

        
<!-- <div class="padding text-white text-center mtop">

    <% @drive_date.each do |i| %>
    <div style="margin-top: 12px;">Date:<%=i.date%></div>
    PROFILE :<%=i.profile%> <br>
    
    <%end%>
</div> -->

app/views/home/interviewer.html.erb
<% if @list%>
    <%="No Candiate Assigned You For Interview Yet"%>
<%else%>
<% @list.each do |i| %>
Name :<%= i.name %> <br>
Time :<%= i.attend_time %> <br>
Date :<%= i.interview_date %> <br>
<%end%>
<%end%>

app/views/home/setdrivedate.html.erb
<% if current_user.role=="admin" %>
  <% if notice %>
    <%= notice %>
      <%end%>




        <div class="col-lg-5 mx-lg-auto card shadow mt-5">
          <div class="card-header">
            <h3 class="card-title text-center">Drive Date</h3>
          </div>
          <div class="card-body">



            <%= form_with method: :post , url:set_path do |form| %>


              <div class="form-group mb-2">
                <%= form.label :Date%><br>
                  <%= form.date_field :date,class: "form-control form-control-lg" %>
              </div>


              <div class="form-group mb-2">
                <%= form.label :Profile%><br>
                  <%= form.text_field :profile , class: "form-control form-control-lg" %>
              </div>

              <%= form.submit "Setdate" %>
          </div>
          <% end %>


        </div>
        </div>

        <% else%>
          <%= "sorry invalid user permission" %>
            <%end%>

app/views/home/track.html.erb
   <div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog" alt=""/>
                    <div class="file btn btn-lg btn-primary">
                        Change Photo
                        <input type="file" name="file"/>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                            <h5>
                                <p><%=@user.name%></p>
                            </h5>
                            <h6>
                                Web Developer and Designer
                            </h6>
                            <!-- <p class="proile-rating">RANKINGS : <span>8/10</span></p> -->
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <!-- <li class="nav-item">
                            <%= link_to "edit_user_profile" , edit_user_profile_path%>
                         
                        </li> -->
                        <!-- <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                        </li> -->
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <!-- <input type="submit" class="profile-edit-btn" name="btnAddMore" > -->
                <%= link_to "Candidate" ,candidate_path%>
                
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-work">
                    <p>WORK LINK</p>
                    <a href="">Website Link</a><br/>
                    <a href="">Bootsnipp Profile</a><br/>
                    <a href="">Bootply Profile</a>
                    <p>SKILLS</p>
                    <a href="">Web Designer</a><br/>
                    <a href="">Web Developer</a><br/>
                    <a href="">WordPress</a><br/>
                    <a href="">WooCommerce</a><br/>
                    <a href="">PHP, .Net</a><br/>
                </div>
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Name</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p><%=@user.name%></p>
                                    </div>
                                </div>
                         
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Email</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p><%=@user.email%></p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Interviewer Name</label>
                                    </div>
                                    <div class="col-md-6">
                                        <% if @user.inter?%>
                                           <p><%= @user.inter%></p>
                                           <%else%>
                                           <p> <%= "To be Decide"%> </p>
 
                                           <%end%>

                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <label>interview Time</label>
                                    </div>

                                    <div class="col-md-6">
                                        <% if @user.inter?%>
                                        <p><%= @user.attend_time%></p>
                                        <%else%>
                                        <p> <%= "To be Decide"%> </p>
                                        <%end%>
                                    </div>
                                 
                                </div>
                                  


                                <div class="row">
                                    <div class="col-md-6">
                                        <label>interview date</label>
                                    </div>

                                    <div class="col-md-6">
                                        <% if @user.interview_date?%>
                                        <p><%= @user.interview_date%></p>
                                        <%else%>
                                         <p> <%= "To be Decide"%> </p>
                                        <%end%>
                                    </div>
                                 
                                </div>
                                 
                                
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>First Round</label>
                                    </div>

                                    <div class="col-md-6">
                                        <% if @user.first?%>
                                        <p><%= @user.first%></p>
                                        <%else%>
                                        <p> <%= "Not cleared"%> </p>
                                        <%end%>
                                    </div>
                                 
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Second Round</label>
                                    </div>

                                    <div class="col-md-6">
                                        <% if @user.second?%>
                                        <p><%= @user.second%></p>
                                        <%else%>
                                        <p> <%= "Not cleared"%> </p>
                                        <%end%>
                                    </div>
                                 
                                </div>


                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Third Round</label>
                                    </div>

                                    <div class="col-md-6">
                                        <% if @user.third?%>
                                        <p><%= @user.third%></p>
                                        <%else%>
                                        <p> <%= "Not cleared"%> </p>
                                        <%end%>
                                    </div>
                                 
                                </div>









                    </div>
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        
                                    </div>
                                    <div class="col-md-6">
                                        <p>Expert</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Hourly Rate</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>10$/hr</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Total Projects</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>230</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>English Level</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>Expert</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Availability</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>6 months</p>
                                    </div>
                                </div>
                        <div class="row">
                            <div class="col-md-12">
                                <label>Your Bio</label><br/>
                                <p>Your detail description</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>           
</div>

app/views/home/updatedata.html.erb
sasas